#! /bin/bash

cnt=0;
sum=$(($#+0));
for i in $@ ; do
  if [ ${cnt} -eq 0 ]; then
    echo "[INFO] tranfering ${i}"
  else
    printf "[INFO] in ${i}: \n"
    scp $1 "ubuntu-${i}:/home/test" 
    printf "\n"
  fi
  let cnt+=1
done
    
echo "[INFO]execute finished"
